# ќбщий уровень Ч только ошибки и предупреждени€
org.slf4j.simpleLogger.defaultLogLevel=warn

# —вой код (замени пакет на свой, если другой) Ч уровень info
org.slf4j.simpleLogger.log.work4=info

# ‘ормат: краткий, без даты (дату можно оставить, раскомментировав строку)
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
